build:
	sudo docker build  -t pejmanhkh/php72 .
version:
	sudo docker run -it -v $(shell pwd)/src/:/root/src/ pejmanhkh/php72 /usr/local/php72/bin/php -v
sh:
	sudo docker run -it -v $(shell pwd)/src/:/root/src/ pejmanhkh/php72 sh
