version: "3.9"
services:
  nginx:
    image: pejmanhkh/nginx-apache
    ports:
      - "8082:80" 
      - "8081:8080" 
    container_name: mydirectadmin
    volumes:
      - ./apache2/:/etc/apache2/
      - ./nginx/:/etc/nginx/
      - ./directadmin/:/usr/local/directadmin/
      - ./www/:/var/www/html/
      - ./home/:/home/
      - ./log/:/var/log/
      - ./php72/sockets:/usr/local/php72/sockets/
    restart: unless-stopped
  php72:
    image: pejmanhkh/php72
    ports:
      - "9000:9000"
    volumes:
      - ./home/:/home/
      - ./directadmin/:/usr/local/directadmin/
      - ./php72/sockets:/usr/local/php72/sockets/
      - ./log/:/var/log/
      - ./php72/etc:/usr/local/etc
    container_name: php72
    restart: unless-stopped
    
