version: "3.9"
services:
  nginx:
    image: pejmanhkh/directadmin
    ports:
      - "8082:80" 
      - "8081:8080" 
    container_name: mydirectadmin
    volumes:
      - ./apache2/:/etc/apache2/
      - ./nginx/:/etc/nginx/
      - ./directadmin/:/usr/local/directadmin/
      - ./www/:/var/www/html/
      - ./home/:/home/
      - ./log/:/var/log/
    restart: unless-stopped
