<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://www.google.com/');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Authority: www.google.com';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
$headers[] = 'Accept-Language: en-US,en;q=0.9,fa;q=0.8';
$headers[] = 'Cache-Control: no-cache';
$headers[] = 'Cookie: CONSENT=PENDING+366; SOCS=CAISHAgCEhJnd3NfMjAyMzAyMTYtMF9SQzEaAmVuIAEaBgiAttWfBg; HSID=AX97oblmfcFUpZXQS; SSID=AU4fm0ImiRBgmeIVG; APISID=N4w-awUarZ3y87i2/A01g7YCOymImJAKc8; SAPISID=Xe3V5e2IqPcutnfE/Aa0Vn0XX5apjL1wOy; __Secure-1PAPISID=Xe3V5e2IqPcutnfE/Aa0Vn0XX5apjL1wOy; __Secure-3PAPISID=Xe3V5e2IqPcutnfE/Aa0Vn0XX5apjL1wOy; SID=XAiaPyuU6kEUmRQ5EdtuivwR6NLB-OUjPRxwUga8XcCkRcmnVqq8jbq52ttlQx9t8mtjzg.; __Secure-1PSID=XAiaPyuU6kEUmRQ5EdtuivwR6NLB-OUjPRxwUga8XcCkRcmn93GTVvQToZeqVQGrFyVrIw.; __Secure-3PSID=XAiaPyuU6kEUmRQ5EdtuivwR6NLB-OUjPRxwUga8XcCkRcmnJJsN8kBbaG9wTa4E9WhoSg.; OTZ=7047738_42_42_114990_38_379890; SEARCH_SAMESITE=CgQIsJgB; AEC=AUEFqZfFYacSy282RB1Wn_upfwYA1x4EsXtxstc4_zikXXkX_d-MzOGacQ; 1P_JAR=2023-6-11-7; __Secure-1PSIDTS=sidts-CjEBLFra0hBgAmDwGoF3GcdXfmT5psiKpYWSAsDJdlWDtZPDI29EcE7qFUM7_dVHH1fPEAA; __Secure-3PSIDTS=sidts-CjEBLFra0hBgAmDwGoF3GcdXfmT5psiKpYWSAsDJdlWDtZPDI29EcE7qFUM7_dVHH1fPEAA; NID=511=MJvqsE_tNBxdYyNe_ujFCBgENBAnj1GnO20OteGuGF72ZNfnvJsYNcVAD2uDLEMJld_RCpcvt6aRbY_zmBXzD7G1TFF9HxnZOFN4Jtr5-Y2oW5yQmPrlzRiSk4FWpkrsy4hXOnvmbmnqwslmgewxHPLsbd7BZjNR5gmKhZl9xzYpv-MZFu1YQTghnw3izLrW1CpFFclFkvMKUSqu-DhPdKUDgcsw6kFdjK5RMwcnPv1rc_az_xa3QY4lw7idu57Apxf9_Mf8_ANOnyU0JBlD5PTi7zCMDjNMYzXBc3nodeQecKukcc0AE73RqX5z_pyrTITKxZJ8zEQHTu2wrG0k; DV=I0GqtKtru4hRIBy4P1MyROtg_mmUipjJ1eQobKS9LwMAAGAUsbpzQL8yIwEAAICIXxvmwpdnSwAAAIg4XiIVaGUaGAAAAA; SIDCC=AP8dLtztWbaL_wua-myBjgNf5SK8kOYt5vW4j2fEymdvWbVzYRyZ_WdKEDZMOCneD2I5GzyVszY; __Secure-1PSIDCC=AP8dLtxS-a0QAzJZ73OZcuvWZieSaKPqP91kYoWrky9XkFuPS55GgaBffM2GpQ0WJcpT4rCyEVOX; __Secure-3PSIDCC=AP8dLtyuRlRwWw9gF6IZSUGSJzzXtkgwaiiNQkkg0VeuCc5mp0d6YS_c_tbxU1VSdXgI05KFUvQ';
$headers[] = 'Pragma: no-cache';
$headers[] = 'Sec-Ch-Ua: \"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"';
$headers[] = 'Sec-Ch-Ua-Arch: \"x86\"';
$headers[] = 'Sec-Ch-Ua-Bitness: \"64\"';
$headers[] = 'Sec-Ch-Ua-Full-Version: \"107.0.5304.110\"';
$headers[] = 'Sec-Ch-Ua-Full-Version-List: \"Google Chrome\";v=\"107.0.5304.110\", \"Chromium\";v=\"107.0.5304.110\", \"Not=A?Brand\";v=\"24.0.0.0\"';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'Sec-Ch-Ua-Model: \"\"';
$headers[] = 'Sec-Ch-Ua-Platform: \"Linux\"';
$headers[] = 'Sec-Ch-Ua-Platform-Version: \"5.19.0\"';
$headers[] = 'Sec-Ch-Ua-Wow64: ?0';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-Site: same-origin';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36';
$headers[] = 'X-Client-Data: CIy2yQEIprbJAQipncoBCPmFywEIk6HLAQinjM0B';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo $result;