version: "3.9"
services:
  nginx:
    image: pejmanhkh/nginx-php81
    ports:
      - "8888:80"    
    container_name: mynginx
    volumes:
      - ./nginx/:/etc/nginx/
      - ./php81/:/etc/php81/
      - ./home/:/home/
      - ./log/:/var/log/
    restart: unless-stopped
