build:
	sudo docker build -t pejmanhkh/php72-ext .
run:
	sudo docker run -it pejmanhkh/php72-ext /root/php-7.2.34/bin/php -v

modules:
	sudo docker run -it pejmanhkh/php72-ext /root/php-7.2.34/bin/php -m